---
- name: Ensure Nvidia-Docker v1.x volumes are removed
  docker_volume:
    driver: nvidia-docker
    name: "*"
    state: absent

- name: Ensure Nvidia-Docker v1.x is Removed
  package:
    name: nvidia-docker
    state: absent

- include_tasks: centos.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Install Nvidia-Docker
  package:
    name: nvidia-docker2
    state: latest

- name: Configure default runtime
  lineinfile:
    insertbefore: '\"runtimes\":\s\{'
    line: '    "default-runtime": "nvidia",'
    path: /etc/docker/daemon.json

- name: Kill existing docker process
  shell: "pkill -SIGHUP dockerd"

- name: Test gpu container
  command: "docker run --rm nvidia/cuda nvidia-smi"
