- name: add nvidia-docker apt-key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: add nvidia-docker apt repository
  get_url:
    url: "https://nvidia.github.io/nvidia-docker/{{ ansible_lsb.id|lower }}{{ ansible_distribution_version }}/nvidia-docker.list"
    dest: /etc/apt/sources.list.d/nvidia-docker.list

- name: Update apt
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items:
    - nvidia-384
    - "{{ nvidia_docker_package_name }}"
