- name: add nvidia-docker apt-key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: add nvidia-docker apt repository
  get_url:
    url: "https://nvidia.github.io/nvidia-docker/{{ ansible_lsb.codename|lower }}/nvidia-docker.list"
    dest: /etc/apt/sources.list.d/nvidia-docker.list

- name: Update apt
  apt:
    update_cache: yes
